### ISSUE TITLE
hlt instruction in x86_64 causes the 'impossible happened' error

### ISSUE THREAD

**Issue by andreafioraldi** [angr/pyvex#103]
```assembly
.text:00000000004049A0                                   public start
.text:00000000004049A0                   start           proc near               ; DATA XREF: LOAD:0000000000400018↑o
.text:00000000004049A0                   ; __unwind {
.text:00000000004049A0 31 ED                             xor     ebp, ebp
.text:00000000004049A2 49 89 D1                          mov     r9, rdx         ; rtld_fini
.text:00000000004049A5 5E                                pop     rsi             ; argc
.text:00000000004049A6 48 89 E2                          mov     rdx, rsp        ; ubp_av
.text:00000000004049A9 48 83 E4 F0                       and     rsp, 0FFFFFFFFFFFFFFF0h
.text:00000000004049AD 50                                push    rax
.text:00000000004049AE 54                                push    rsp             ; stack_end
.text:00000000004049AF 49 C7 C0 50 3C 41+                mov     r8, offset fini ; fini
.text:00000000004049B6 48 C7 C1 E0 3B 41+                mov     rcx, offset init ; init
.text:00000000004049BD 48 C7 C7 00 2A 40+                mov     rdi, offset main ; main
.text:00000000004049C4 E8 77 DC FF FF                    call    ___libc_start_main
.text:00000000004049C9 F4                                hlt   ; <--- DOH
.text:00000000004049C9                   ; } // starts at 4049A0
.text:00000000004049C9                   start           endp
```
Lifting the start procedure in x86_64 give me an error on the hlt instruction:

```python
>>> pyvex.IRSB("\xf4", 0, archinfo.ArchX86()).pp()
IRSB {
   t0:Ity_I32

   00 | ------ IMark(0x0, 1, 0) ------
   NEXT: PUT(eip) = 0x00000001; Ijk_SigTRAP
}
>>>
>>> pyvex.IRSB("\xf4", 0, archinfo.ArchAMD64()).pp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyvex\block.py", line 72, in __init__
    lift(self, data, max_bytes, max_inst, bytes_offset, opt_level, traceflags)
  File "C:\Python27\lib\site-packages\pyvex\lift\__init__.py", line 100, in lift
    raise PyVEXError('\n\n'.join(errors))
pyvex.errors.PyVEXError:
vex: the `impossible' happened:
   Not enough bytes given to decode even a single instruction
```

**Comment by ltfish** [comment]
LibVEX does not support `hlt`, and you should never execute a `hlt` instruction anyway.

**Comment by andreafioraldi** [comment]
Ok, thanks.
I need to lift all functions in a binary but gcc inserts hlt in start (but it's never executed).
How do you handle this in angr?

**Comment by ltfish** [comment]
That single instruction is modeled as a "terminator" in CFGFast, using a `SimProcedure`. We treat it in the same way as any instruction that VEX does not like.

**Comment by zardus** [comment]
If you really need VEX IR for `hlt`, you might be able to use the `spotter` lift-assistance stuff being developed by @subwire and @Nilocunger to specify a translation for just that instruction.

**Comment by andreafioraldi** [comment]
thanks for the advice!
