### ISSUE TITLE
Unable to Install pyvex

### ISSUE THREAD

**Issue by NaveenBoggarapu** [angr/pyvex#30]
Hi,

I am unable to install pyvex on my machine(ubuntu 14.04), I am using pip for installation, and this machine is behind a proxy.

Following is the error message.

`naveen@CRD:~$ sudo pip install --proxy=http://xxxxx:xxxxx@xxxxx:80 pyvex
Downloading/unpacking pyvex
  Downloading pyvex-4.6.1.27.tar.gz (5.4MB): 5.4MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pyvex/setup.py) egg_info for package pyvex
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pyvex/setup.py", line 20, in <module>
        v.write(urllib2.urlopen(VEX_URL).read())
      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 404, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 422, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
        return self.do_open(httplib.HTTPSConnection, req)
      File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pyvex/setup.py", line 20, in <module>

```
v.write(urllib2.urlopen(VEX_URL).read())
```

  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen

```
return _opener.open(url, data, timeout)
```

  File "/usr/lib/python2.7/urllib2.py", line 404, in open

```
response = self._open(req, data)
```

  File "/usr/lib/python2.7/urllib2.py", line 422, in _open

```
'_open', req)
```

  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain

```
result = func(*args)
```

  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open

```
return self.do_open(httplib.HTTPSConnection, req)
```

  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open

```
raise URLError(err)
```

urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pyvex
Storing debug log for failure in /home/naveen/.pip/pip.log
`

**Comment by rhelmot** [comment]
@zardus looks like you gotta make the vex download use the proxy if one is provided...
