### ISSUE TITLE
Unable to import angr after successful installation in MAC

### ISSUE THREAD

**Issue by H4rryp0tt3r** [angr/pyvex#33]
I installed angr framework with <code>pip install angr</code>

And when I tried importing angr, it gives me below error. Is there anything I'm missing?

>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/Library/Python/2.7/site-packages/angr/project.py", line 11, in <module>
    import simuvex
  File "/Library/Python/2.7/site-packages/simuvex/__init__.py", line 9, in <module>
    from .s_state import SimState
  File "/Library/Python/2.7/site-packages/simuvex/s_state.py", line 11, in <module>
    import claripy
  File "/Library/Python/2.7/site-packages/claripy/__init__.py", line 17, in <module>
    from . import backends as _backends_module
  File "/Library/Python/2.7/site-packages/claripy/backends/__init__.py", line 1, in <module>
    from .backend_z3 import BackendZ3
  File "/Library/Python/2.7/site-packages/claripy/backends/backend_z3.py", line 45, in <module>
    raise ClaripyZ3Error("Unable to find %s", z3_library_file)
claripy.errors.ClaripyZ3Error: ('Unable to find %s', 'libz3.dylib')

**Comment by zardus** [comment]
MacOS... We're gonna have to wait for some pro with MacOS to come along :-)

**Comment by ltfish** [comment]
Should be resolved by https://github.com/angr/claripy/issues/4 . Please reopen this issue if it's not working for you.
