### ISSUE TITLE
Type Error - calling str() on IRSB.Expressions or Statements returns bytes.

### ISSUE THREAD

**Issue by SjRNMzU** [angr/pyvex#93]
I had this exception whilst using pyvex. 

```
Traceback (most recent call last):
  File "symbol_pyvexer.py", line 68, in <module>
    symbol_fill_bytes(symb)
  File "symbol_pyvexer.py", line 57, in symbol_fill_bytes
    symb.gen_vex_features()
  File "../classes/symbol.py", line 80, in gen_vex_features
    vex['expressions'] = list( map( lambda x: { 'tag':x.tag, 'value': str(x) }, irsb.expressions) )
  File "../classes/symbol.py", line 80, in <lambda>
    vex['expressions'] = list( map( lambda x: { 'tag':x.tag, 'value': str(x) }, irsb.expressions) )
  File "/usr/local/lib/python3.5/dist-packages/pyvex/expr.py", line 647, in __str__
    return "%s(%s):%s" % (self.cee, ','.join(str(a) for a in self.args), self.retty)
TypeError: __str__ returned non-string (type bytes)
```

**Comment by SjRNMzU** [comment]
Here's my code.


```
irsb = pyvex.IRSB(function_bytes, address, archinfo.ArchAMD64())
vex = {}
vex['expressions'] = list( map( lambda x: { 'tag':x.tag, 'value': str(x) }, irsb.expressions) )
```

**Comment by rhelmot** [comment]
Oh boy! So our Python 3 support for this is pretty faltering - if you want a quick fix the easiest answer is “use Python 2”. However this is important and I will look into it soon.
