### ISSUE TITLE
can't load pyvex.dll

### ISSUE THREAD

**Issue by ramhillel** [angr/pyvex#95]
After successful installation on windows via pip install, I'm encountered with this issue when trying to import pyvex:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Miniconda2\lib\site-packages\pyvex\__init__.py", line 36, in <module>
    pvc = _find_c_lib()
  File "C:\Program Files\Miniconda2\lib\site-packages\pyvex\__init__.py", line 30, in _find_c_lib
    lib = ffi.dlopen(pyvex_path)
  File "C:\Program Files\Miniconda2\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Program Files\Miniconda2\lib\site-packages\cffi\api.py", line 795, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Program Files\Miniconda2\lib\site-packages\cffi\api.py", line 791, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library C:\Program Files\Miniconda2\lib\site-packages\pyvex\lib\pyvex.dll: error 0xc1
```

I changed the permissions to pyvex.dll and pyvex.lib, and still get the same result.

Also, I successfully installed angr, also via pip, but when trying to import angr get the same error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "angr\__init__.py", line 12, in <module>
    from .sim_procedure import SimProcedure
  File "angr\sim_procedure.py", line 388, in <module>
    from angr.sim_type import SimTypePointer
  File "angr\sim_type.py", line 991, in <module>
    from .state_plugins.view import SimMemView
  File "angr\state_plugins\__init__.py", line 4, in <module>
    from .posix import *
  File "angr\state_plugins\posix.py", line 4, in <module>
    from ..storage.file import SimFile
  File "angr\storage\__init__.py", line 1, in <module>
    from .file import SimFile
  File "angr\storage\file.py", line 306, in <module>
    from ..state_plugins.symbolic_memory import SimSymbolicMemory
  File "angr\state_plugins\symbolic_memory.py", line 9, in <module>
    from ..storage.memory import SimMemory
  File "angr\storage\memory.py", line 9, in <module>
    from ..engines.vex.ccall import _get_flags
  File "angr\engines\__init__.py", line 1, in <module>
    from .successors import SimSuccessors
  File "angr\engines\successors.py", line 353, in <module>
    from ..calling_conventions import SYSCALL_CC
  File "angr\calling_conventions.py", line 4, in <module>
    import archinfo
  File "C:\Program Files\Miniconda2\lib\site-packages\archinfo\__init__.py", line 6, in <module>
    from .arch import *
  File "C:\Program Files\Miniconda2\lib\site-packages\archinfo\arch.py", line 7, in <module>
    import pyvex as _pyvex
  File "C:\Program Files\Miniconda2\lib\site-packages\pyvex\__init__.py", line 36, in <module>
    pvc = _find_c_lib()
  File "C:\Program Files\Miniconda2\lib\site-packages\pyvex\__init__.py", line 30, in _find_c_lib
    lib = ffi.dlopen(pyvex_path)
  File "C:\Program Files\Miniconda2\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Program Files\Miniconda2\lib\site-packages\cffi\api.py", line 795, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Program Files\Miniconda2\lib\site-packages\cffi\api.py", line 791, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library C:\Program Files\Miniconda2\lib\site-packages\pyvex\lib\pyvex.dll: error 0xc1
```

Thanks,
Ram

**Comment by ltfish** [comment]
It seems that you are trying to load a 64-bit pyvex.dll to a 32-bit Python. Is that the case?

**Comment by ramhillel** [comment]
Unfortunately no. This is 64-bit python, on 64-bit windows.

This is the first line in python interpreter in the command line:
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jun 29 2016, 11:07:13) [MSC v.1500 **64 bit** (AMD64)] on win32

**Comment by ltfish** [comment]
Is the `pyvex.dll` a 32-bit library then?

`0xc1` is `ERROR_BAD_EXE_FORMAT` in Windows. I think it's either the `pyvex.dll` is somehow broken, or one of its dependencies is broken.

**Comment by ltfish** [comment]
You might want to see if you can load that `pyvex.dll` and all of its dependencies in Dependency Walker.

**Comment by ramhillel** [comment]
That's right. pip install pyvex running without errors, but is installing the 32-bit version. How can I force it to install the 64-bit version?
Happens the same when using "python -m pip install pyvex"

**Comment by ramhillel** [comment]
For some reason, when I'm installing to python 32-bit it's installing the 64-bit pyvex version, and vice versa.
Any idea why it happen?

**Comment by ltfish** [comment]
I don't think we have wheels built for Windows on PyPI (see [here](https://pypi.python.org/pypi/pyvex)). Therefore it must be built on your machine, with Visual Studio. So it seems to me that it is using the wrong version of `cl`. I would suggest you to run `python -m pip install pyvex` in a x64 native Visual Studio command line prompt for your Python 64-bit install.

**Comment by ramhillel** [comment]
I uninstalled python and installed the latest 64-bit version. Installed pyvex as suggested (python -m pip install pyvex in a x64 native Visual Studio command line prompt) and still it's installing the 32-bit version.
![capture](https://user-images.githubusercontent.com/8492254/31334520-47dcef86-acf7-11e7-8aa9-41247b447cbf.PNG)

**Comment by ltfish** [comment]
I'm out of ideas. But I can tell you how to debug this. We call `nmake` on `Makefile-msvc` under `/pyvex_c` to build PyVEX. The related code is [here](https://github.com/angr/pyvex/blob/master/setup.py#L90). Set a breakpoint there, make a copy of the command line, and manually run it to compile `pyvex.dll` and see if it solves the problem for you. If not, at least that's a good start to debug this issue.

**Comment by ramhillel** [comment]
Thanks! I'll try it and update for any conclusions.

**Comment by ltfish** [comment]
It might be easier for you to debug the PyVEX installation issue by first checking out the repo to your local disk, modify the setup.py as you wish (like setting breakpoints), and then do `python -m pip install .` inside the repo.

**Comment by hi-T0day** [comment]
After having installed the PyVex in Windows 7 via VS2017 Command line, it raised the same error when import pyvex in Python
```
OSError: cannot load library 'pyvex\lib\pyvex.dll': error 0xc1.  Additionally, c
types.util.find_library() did not manage to locate a library called 'pyvex\\lib\
\pyvex.dll'
```
Any solutions about it?

**Comment by ltfish** [comment]
@hi-T0day Make sure both your `pyvex.dll` and you Python are 64-bit (or both of them are 32-bit). Loading a 32-bit library in a 64-bit Python install (or loading a 64-bit library in a 32-bit Python process) will give you error 0xc1.

**Comment by hi-T0day** [comment]
@ltfish  Thanks for you suggestion. I got it :) I reinstall the 32-bit Python and it seems fine now.

**Comment by MostafaSoliman** [comment]
I came across this issue, to build x64 dlls make sure you start VC cmd is started with amd64 env variables to load the x64 cl compiler.
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>vcvarsall.bat amd64
```
